name: E2E Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - "mrc-*"
jobs:
  part-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run E2E shard
        uses: ./.github/actions/run-e2e-shard
        with:
          shard: 1
  part-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run E2E shard
        uses: ./.github/actions/run-e2e-shard
        with:
          shard: 2
  part-3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run E2E shard
        uses: ./.github/actions/run-e2e-shard
        with:
          shard: 3
  part-4:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run E2E shard
        uses: ./.github/actions/run-e2e-shard
        with:
          shard: 4
  part-5:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run E2E shard
        uses: ./.github/actions/run-e2e-shard
        with:
          shard: 5
  part-6:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run E2E shard
        uses: ./.github/actions/run-e2e-shard
        with:
          shard: 6
