name: E2E Tests Part 4
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - "mrc-*"
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Run E2E shard
        uses: ./.github/actions/run-e2e-shard
        with:
          shard: 4
