name: Lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - "mrc-*"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Prebuild (generate version)
        run: npm run prebuild
      - name: Lint
        run: npm run lint  
